"""Gherkin feature file formatter.

Takes raw generated Gherkin content and saves it as a
properly structured .feature file.
"""

import os
import re
from datetime import datetime
from rich.console import Console

console = Console()

OUTPUT_DIR = "output"

HEADER_TEMPLATE = """# Auto-generated Gherkin feature file
# Generated by AI Test Case Generator
# Source: {source}
# Date: {date}
# Provider: {provider}

"""


def _sanitise_filename(source: str) -> str:
    """Convert a URL or description into a safe .feature filename."""
    name = source.replace("https://", "").replace("http://", "")
    name = re.sub(r"[^a-zA-Z0-9]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")

    if len(name) > 60:
        name = name[:60]

    return f"{name}.feature"


def save_gherkin_tests(
    code: str,
    source: str,
    provider: str = "anthropic",
) -> str:
    """Save generated Gherkin feature content to a .feature file.

    Args:
        code: The generated Gherkin feature content.
        source: The URL or description used to generate tests.
        provider: The LLM provider used.

    Returns:
        The path to the saved file.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    filename = _sanitise_filename(source)
    filepath = os.path.join(OUTPUT_DIR, filename)

    header = HEADER_TEMPLATE.format(
        source=source,
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        provider=provider,
    )

    full_content = header + code + "\n"

    with open(filepath, "w") as f:
        f.write(full_content)

    console.print(f"[green]✓[/green] Saved: [bold]{filepath}[/bold]")
    return filepath
