"""Playwright test stub formatter.

Takes raw generated test code and saves it as a properly
structured Python test file ready to run with pytest.
"""

import os
from datetime import datetime
from rich.console import Console

from src.formatters.utils import _sanitise_name

console = Console()

OUTPUT_DIR = "output"  # kept for backwards-compat; not used internally

HEADER_TEMPLATE = '''"""Auto-generated Playwright tests.

Generated by AI Test Case Generator
Source: {source}
Date: {date}
Provider: {provider}

Run with: pytest {filename} -v
"""

'''


def _sanitise_filename(source: str) -> str:
    """Convert a URL or description into a safe filename."""
    return f"test_{_sanitise_name(source)}_playwright.py"


def save_playwright_tests(
    code: str,
    source: str,
    provider: str = "anthropic",
    output_dir: str = "output",
) -> str:
    """Save generated Playwright test code to a file.

    Args:
        code: The generated Python test code.
        source: The URL or description used to generate tests.
        provider: The LLM provider used.
        output_dir: Directory to write the test file into.

    Returns:
        The path to the saved file.
    """
    os.makedirs(output_dir, exist_ok=True)

    filename = _sanitise_filename(source)
    filepath = os.path.join(output_dir, filename)

    header = HEADER_TEMPLATE.format(
        source=source,
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        provider=provider,
        filename=filename,
    )

    # Add header if the generated code doesn't already have imports
    if "import pytest" not in code:
        code = "import pytest\nfrom playwright.sync_api import Page, expect\n\n" + code

    full_content = header + code + "\n"

    with open(filepath, "w") as f:
        f.write(full_content)

    console.print(f"[green]✓[/green] Saved: [bold]{filepath}[/bold]")
    return filepath
