"""Pytest conftest.py — auto-generated by AI Test Case Generator.

Generated: 2026-03-11 10:26

Provides Playwright browser fixtures for generated tests.
Run all tests with:
    pytest output/ -v

Options:
    pytest output/ -v --headed          # run with visible browser
    pytest output/ -v --slowmo 500       # slow down actions by 500ms
    pytest output/ -v --base-url URL     # override the base URL
"""

import pytest
from playwright.sync_api import sync_playwright, Page, Browser, BrowserContext


def pytest_addoption(parser):
    """Register custom CLI options for Playwright tests."""
    parser.addoption(
        "--headed",
        action="store_true",
        default=False,
        help="Run tests in headed (visible) browser mode.",
    )
    parser.addoption(
        "--slowmo",
        type=int,
        default=0,
        help="Slow down Playwright actions by N milliseconds.",
    )
    parser.addoption(
        "--base-url",
        type=str,
        default=None,
        help="Override the base URL for all tests.",
    )


@pytest.fixture(scope="session")
def browser(request) -> Browser:
    """Launch a Playwright Chromium browser for the test session."""
    headed = request.config.getoption("--headed")
    slowmo = request.config.getoption("--slowmo")

    pw = sync_playwright().start()
    browser = pw.chromium.launch(
        headless=not headed,
        slow_mo=slowmo,
    )
    yield browser
    browser.close()
    pw.stop()


@pytest.fixture(scope="function")
def context(browser: Browser) -> BrowserContext:
    """Create a fresh browser context for each test."""
    ctx = browser.new_context(
        viewport={"width": 1280, "height": 720},
    )
    yield ctx
    ctx.close()


@pytest.fixture(scope="function")
def page(context: BrowserContext, request) -> Page:
    """Create a new page for each test with screenshot-on-failure."""
    pg = context.new_page()
    yield pg

    # Screenshot on failure
    if request.node.rep_call and request.node.rep_call.failed:
        test_name = request.node.name
        screenshot_dir = os.path.join(os.path.dirname(__file__), "screenshots")
        os.makedirs(screenshot_dir, exist_ok=True)
        pg.screenshot(path=os.path.join(screenshot_dir, f"{test_name}.png"))

    pg.close()


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Attach test result info to the request node for screenshot fixture."""
    import pytest
    outcome = yield
    rep = outcome.get_result()
    setattr(item, f"rep_{rep.when}", rep)


@pytest.fixture(scope="session")
def base_url(request) -> str:
    """Provide the base URL, configurable via --base-url or env var."""
    url = request.config.getoption("--base-url")
    if url:
        return url
    import os
    return os.environ.get("PLAYWRIGHT_BASE_URL", "")
