"""Auto-generated Playwright tests.

Generated by AI Test Case Generator
Source: https://practicetestautomation.com/practice-test-login/
Date: 2026-03-11 10:24
Provider: demo

Run with: pytest test_practicetestautomation_com_practice_test_login_playwright.py -v
"""

import pytest
from playwright.sync_api import Page, expect


BASE_URL = "https://practicetestautomation.com/practice-test-login/"


class TestLoginHappyPath:
    """Happy path tests for login functionality."""

    def test_successful_login_with_valid_credentials(self, page: Page):
        """Verify user can log in with valid username and password."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page).to_have_url_matching(".*logged-in-successfully.*")

    def test_successful_login_shows_congratulations(self, page: Page):
        """Verify logged-in page contains success message."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator(".post-title")).to_contain_text("Logged In Successfully")

    def test_successful_login_displays_logout_button(self, page: Page):
        """Verify Log out button is visible after successful login."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.get_by_role("link", name="Log out")).to_be_visible()

    def test_logout_after_successful_login(self, page: Page):
        """Verify user can log out and return to the main page."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        page.get_by_role("link", name="Log out").click()
        expect(page).to_have_url("https://practicetestautomation.com/")


class TestLoginNegative:
    """Negative tests for login functionality."""

    def test_login_with_invalid_username(self, page: Page):
        """Verify error message when username is incorrect."""
        page.goto(BASE_URL)
        page.locator("#username").fill("incorrectUser")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()
        expect(page.locator("#error")).to_contain_text("Your username is invalid!")

    def test_login_with_invalid_password(self, page: Page):
        """Verify error message when password is incorrect."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("incorrectPassword")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()
        expect(page.locator("#error")).to_contain_text("Your password is invalid!")

    def test_login_with_empty_username(self, page: Page):
        """Verify error when username field is left empty."""
        page.goto(BASE_URL)
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()
        expect(page.locator("#error")).to_contain_text("Your username is invalid!")

    def test_login_with_empty_password(self, page: Page):
        """Verify error when password field is left empty."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()
        expect(page.locator("#error")).to_contain_text("Your password is invalid!")

    def test_login_with_both_fields_empty(self, page: Page):
        """Verify error when both fields are empty."""
        page.goto(BASE_URL)
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()


class TestLoginEdgeCases:
    """Edge case tests for login functionality."""

    def test_login_with_sql_injection_in_username(self, page: Page):
        """Verify login is safe from SQL injection in username."""
        page.goto(BASE_URL)
        page.locator("#username").fill("\' OR 1=1 --")
        page.locator("#password").fill("anything")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()
        expect(page).not_to_have_url_matching(".*logged-in-successfully.*")

    def test_login_with_xss_payload_in_username(self, page: Page):
        """Verify login sanitises XSS payloads in username."""
        page.goto(BASE_URL)
        page.locator("#username").fill("<script>alert(\'xss\')</script>")
        page.locator("#password").fill("test")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

    def test_login_with_case_sensitive_username(self, page: Page):
        """Verify username is case-sensitive (Student != student)."""
        page.goto(BASE_URL)
        page.locator("#username").fill("Student")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

    def test_login_with_case_sensitive_password(self, page: Page):
        """Verify password is case-sensitive (password123 != Password123)."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

    def test_login_with_whitespace_username(self, page: Page):
        """Verify login rejects username with leading/trailing spaces."""
        page.goto(BASE_URL)
        page.locator("#username").fill("  student  ")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()


class TestLoginBoundary:
    """Boundary value tests for login functionality."""

    def test_login_with_very_long_username(self, page: Page):
        """Verify system handles extremely long username input."""
        page.goto(BASE_URL)
        page.locator("#username").fill("a" * 500)
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

    def test_login_with_very_long_password(self, page: Page):
        """Verify system handles extremely long password input."""
        page.goto(BASE_URL)
        page.locator("#username").fill("student")
        page.locator("#password").fill("x" * 500)
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

    def test_login_with_single_character_username(self, page: Page):
        """Verify system handles single character username."""
        page.goto(BASE_URL)
        page.locator("#username").fill("a")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

    def test_login_with_special_characters_in_username(self, page: Page):
        """Verify system handles special characters in username."""
        page.goto(BASE_URL)
        page.locator("#username").fill("!@#$%^&*()")
        page.locator("#password").fill("Password123")
        page.locator("#submit").click()
        expect(page.locator("#error")).to_be_visible()

