# Auto-generated Gherkin feature file
# Generated by AI Test Case Generator
# Source: https://example.com/login
# Date: 2026-03-01 10:00
# Provider: anthropic

Feature: User Login
  As a registered user
  I want to log in to my account
  So that I can access the application dashboard

  Background:
    Given I am on the login page

  # Happy Path Tests
  @happy-path
  Scenario: Successful login with valid credentials
    When I enter "user@test.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the "Sign In" button
    Then I should be redirected to the dashboard

  @happy-path
  Scenario: Login with remember me enabled
    When I enter "user@test.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I check the "Remember me" checkbox
    And I click the "Sign In" button
    Then I should be redirected to the dashboard
    And my session should persist after closing the browser

  # Negative Tests
  @negative
  Scenario Outline: Login with invalid credentials
    When I enter "<email>" in the email field
    And I enter "<password>" in the password field
    And I click the "Sign In" button
    Then I should see an error message "<error>"

    Examples:
      | email             | password       | error                |
      | user@test.com     | wrongpassword  | Invalid credentials  |
      | nobody@test.com   | SomePass123!   | Invalid credentials  |
      | not-an-email      | ValidPass123!  | Enter a valid email  |

  @negative
  Scenario: Login with empty email field
    When I leave the email field empty
    And I enter "ValidPass123!" in the password field
    And I click the "Sign In" button
    Then I should see an error message "Email is required"

  @negative
  Scenario: Login with empty password field
    When I enter "user@test.com" in the email field
    And I leave the password field empty
    And I click the "Sign In" button
    Then I should see an error message "Password is required"

  # Edge Case Tests
  @edge-case @security
  Scenario: SQL injection attempt in email field
    When I enter "' OR 1=1 --" in the email field
    And I enter "anything" in the password field
    And I click the "Sign In" button
    Then I should remain on the login page
    And I should see an error message

  @edge-case @security
  Scenario: XSS attempt in email field
    When I enter "<script>alert('xss')</script>" in the email field
    And I enter "test" in the password field
    And I click the "Sign In" button
    Then the script should not execute
    And I should see an error message

  @edge-case
  Scenario: Login with unicode characters in email
    When I enter "\u00fcser@t\u00e9st.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the "Sign In" button
    Then I should see an appropriate error or success message

  @edge-case @security
  Scenario: Brute force protection after multiple failed attempts
    When I attempt to login 6 times with incorrect passwords
    Then I should see a rate limiting message "Too many attempts"
    And further login attempts should be temporarily blocked

  # Boundary Value Tests
  @boundary
  Scenario: Login with maximum length email (254 characters)
    When I enter a 254-character email address
    And I enter "ValidPass123!" in the password field
    And I click the "Sign In" button
    Then the system should handle the input without crashing

  @boundary
  Scenario: Login with minimum length password
    When I enter "user@test.com" in the email field
    And I enter "Ab1!" in the password field
    And I click the "Sign In" button
    Then I should see an error message "Password too short"

  @boundary
  Scenario: Login with maximum length password (128 characters)
    When I enter "user@test.com" in the email field
    And I enter a 128-character password
    And I click the "Sign In" button
    Then the system should handle the input without crashing
