"""Auto-generated Playwright tests.

Generated by AI Test Case Generator
Source: https://example.com/login
Date: 2026-03-01 10:00
Provider: anthropic

Run with: pytest test_login_playwright.py -v
"""

import pytest
from playwright.sync_api import Page, expect


class TestLoginHappyPath:
    """Happy path tests for login functionality."""

    def test_login_with_valid_credentials(self, page: Page):
        """Verify user can log in with valid email and password."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_label("Password").fill("ValidPass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page).to_have_url("https://example.com/dashboard")

    def test_login_with_remember_me(self, page: Page):
        """Verify 'Remember Me' checkbox persists session."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_label("Password").fill("ValidPass123!")
        page.get_by_label("Remember me").check()
        page.get_by_role("button", name="Sign In").click()
        expect(page).to_have_url("https://example.com/dashboard")

    def test_login_redirects_to_original_page(self, page: Page):
        """Verify user is redirected back after login."""
        page.goto("https://example.com/settings")
        # Assume redirect to login
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_label("Password").fill("ValidPass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page).to_have_url("https://example.com/settings")


class TestLoginNegative:
    """Negative tests for login functionality."""

    def test_login_with_invalid_password(self, page: Page):
        """Verify error message when password is incorrect."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_label("Password").fill("wrongpassword")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Invalid credentials")).to_be_visible()

    def test_login_with_unregistered_email(self, page: Page):
        """Verify error when email is not registered."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("nobody@test.com")
        page.get_by_label("Password").fill("SomePass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Invalid credentials")).to_be_visible()

    def test_login_with_empty_email(self, page: Page):
        """Verify validation when email field is empty."""
        page.goto("https://example.com/login")
        page.get_by_label("Password").fill("SomePass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Email is required")).to_be_visible()

    def test_login_with_empty_password(self, page: Page):
        """Verify validation when password field is empty."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Password is required")).to_be_visible()

    def test_login_with_malformed_email(self, page: Page):
        """Verify validation rejects malformed email addresses."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("not-an-email")
        page.get_by_label("Password").fill("ValidPass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Enter a valid email")).to_be_visible()


class TestLoginEdgeCases:
    """Edge case tests for login functionality."""

    def test_login_with_sql_injection_attempt(self, page: Page):
        """Verify login is safe from SQL injection."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("' OR 1=1 --")
        page.get_by_label("Password").fill("anything")
        page.get_by_role("button", name="Sign In").click()
        expect(page).to_have_url("https://example.com/login")

    def test_login_with_xss_payload_in_email(self, page: Page):
        """Verify login sanitises XSS payloads in email field."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("<script>alert('xss')</script>")
        page.get_by_label("Password").fill("test")
        page.get_by_role("button", name="Sign In").click()
        # Page should not execute script
        expect(page.get_by_text("Invalid credentials")).to_be_visible()

    def test_login_with_unicode_email(self, page: Page):
        """Verify login handles unicode characters in email."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("u\u0308ser@t\u00e9st.com")
        page.get_by_label("Password").fill("ValidPass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Invalid credentials")).to_be_visible()

    def test_rapid_login_attempts_rate_limited(self, page: Page):
        """Verify brute force protection after multiple failed attempts."""
        page.goto("https://example.com/login")
        for _ in range(6):
            page.get_by_label("Email").fill("user@test.com")
            page.get_by_label("Password").fill("wrong")
            page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Too many attempts")).to_be_visible()


class TestLoginBoundary:
    """Boundary value tests for login functionality."""

    def test_login_with_max_length_email(self, page: Page):
        """Verify handling of maximum length email (254 chars)."""
        long_email = "a" * 243 + "@test.com"  # 254 chars
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill(long_email)
        page.get_by_label("Password").fill("ValidPass123!")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Invalid credentials")).to_be_visible()

    def test_login_with_minimum_password_length(self, page: Page):
        """Verify validation for password below minimum length."""
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_label("Password").fill("Ab1!")
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_text("Password too short")).to_be_visible()

    def test_login_with_max_length_password(self, page: Page):
        """Verify handling of very long password (128 chars)."""
        long_pass = "Aa1!" * 32  # 128 chars
        page.goto("https://example.com/login")
        page.get_by_label("Email").fill("user@test.com")
        page.get_by_label("Password").fill(long_pass)
        page.get_by_role("button", name="Sign In").click()
        # Should either succeed or show a clear error
        expect(page.locator("body")).to_contain_text(
            "dashboard", timeout=5000
        )
